RochaGerenciamento.MVC/Controllers/PlanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RochaGerenciamento.Domain.Entities;
using RochaGerenciamento.Infra.Contexto;
using RochaGerenciamento.Application.Interfaces;
using RochaGerenciamento.Domain.Enums;

namespace RochaGerenciamento.MVC.Controllers
{
    [Authorize(Roles = "administrador")]
    public class PlanController : BaseController<Plan>
    {
        IConstructionAppService _constructionApp;
        public PlanController(IPlanAppService entityApp, IAppServiceBase<User> userApp, IConstructionAppService constructionApp)
            : base(entityApp, userApp)
        {
            _constructionApp = constructionApp;
            ViewBag.CodeConstruction = new SelectList(_constructionApp.GetAll().ToList(), GeneralField.Code, GeneralField.Name);
        }

        public override ActionResult Edit(int id = 0)
        {
            var entity = _entityApp.GetById(id);
            if (CheckIfExists(entity)) return RedirectToAction("Index");
            ViewBag.CodeConstruction = new SelectList(_constructionApp.GetAll().ToList(), GeneralField.Code, GeneralField.Name, entity.CodeConstruction);
            return View(entity);
        }
    }
}

RochaGerenciamento.MVC/Controllers/PrincipalController.cs
using RochaGerenciamento.Application.Interfaces;
using RochaGerenciamento.Domain.Enums;
using RochaGerenciamento.MVC.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RochaGerenciamento.MVC.Controllers
{
    public class PrincipalController : Controller
    {
        IConstructionAppService _constructionAppService;
        public PrincipalController(IConstructionAppService constructionAppService)
        {
            _constructionAppService = constructionAppService;
            ViewBag.CodeConstruction = new SelectList(_constructionAppService.GetAll().ToList(), GeneralField.Code, GeneralField.Name);
        }

        public JsonResult SetSessionConstruction(int codeConstruction, string nameConstruction)
        {
            
            try
            {
                RochaGerenciamento.Domain.ValueObject.Session.CodeConstruction = codeConstruction;
                RochaGerenciamento.Domain.ValueObject.Session.NameConstruction = nameConstruction;
                return Json(new { Message = "ConstructionChosen", Success = SuccessMessage.ConstructionChosen, Error = String.Empty });
            }
            catch
            {
                return Json(new { Message = "False", Error = ErrorMessage.NotCompleted, Success = String.Empty });
            }
        } 

        public ActionResult Index()
        {
            //if (Authorizer.AutorizaEstoque)
            //    return RedirectToAction("Estoque", "Movimentacao");
            //if (Authorizer.AutorizaPlanejamento)
            //    return RedirectToAction("ItensBaixa", "Movimentacao");
            //if (Authorizer.AutorizaVendedor)
            //    return RedirectToAction("ItensVendidos", "Movimentacao");
            ViewBag.CodeConstruction = new SelectList(_constructionAppService.GetAll().ToList(), GeneralField.Code, GeneralField.Name, RochaGerenciamento.Domain.ValueObject.Session.CodeConstruction);
            return View();
        }

    }
}

RochaGerenciamento.MVC/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RochaGerenciamento.Domain.Entities;
using RochaGerenciamento.Infra.Contexto;
using RochaGerenciamento.Application.Interfaces;
using RochaGerenciamento.Domain.Enums;

namespace RochaGerenciamento.MVC.Controllers
{
    [Authorize(Roles = "administrador")]
    public class ProjectController : BaseController<Project>
    {
        ISubServiceAppService _subServiceApp;
        public ProjectController(IProjectAppService entityApp, IAppServiceBase<User> userApp, ISubServiceAppService subServiceApp)
            : base(entityApp, userApp)
        {
            _subServiceApp = subServiceApp;
            ViewBag.CodeSubService = new SelectList(_subServiceApp.GetAll().ToList(), GeneralField.Code, GeneralField.Name);
            
        }

        public override ActionResult Edit(int id = 0)
        {
            var entity = _entityApp.GetById(id);
            if (CheckIfExists(entity)) return RedirectToAction("Index");
            ViewBag.CodeSubService = new SelectList(_subServiceApp.GetAll().ToList(), GeneralField.Code, GeneralField.Name, entity.CodeSubService);
            return View(entity);
        }
    }
}

RochaGerenciamento.MVC/Views/Project/Create.cshtml
@model RochaGerenciamento.Domain.Entities.Project

@{
    ViewBag.Title = "Create";
}
<div class="innerpage">
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Principal")">Home</a></li>
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Construction")">Obras</a></li>
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Plan")">Planejamentos</a></li>
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Project")">Projetos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Cadastrar Projeto</li>
        </ol>
    </nav>
    @Html.Partial("~/Views/Shared/_mensagemRetorno.cshtml")

    @using (Html.BeginForm())
    {

        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Criar Projeto</legend>

            <div class="form-group">
                <label for="Name">Nome</label>
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = "Insira um Nome", required = true })
            </div>

            <div class="form-group">
                <label for="Value">Valor</label>
                <input id="Value" name="Value" class="form-control" placeholder="Insira um Valor" required/>
            </div>

            <div class="form-group">
                <label for="SubService">Tipo de Sub-Serviço</label>
                @Html.DropDownList("CodeSubService", null, "Selecione", new { @class = "selectpicker" })
            </div>

            <div class="form-group">
                <!-- Submit button !-->
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            </div>
        </fieldset>
    }

</div>

RochaGerenciamento.MVC/Views/Project/Edit.cshtml
@model RochaGerenciamento.Domain.Entities.Project

@{
    ViewBag.Title = "Edit";
}
<div class="innerpage">
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Principal")">Home</a></li>
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Construction")">Obras</a></li>
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Plan")">Planejamentos</a></li>
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Project")">Projetos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editar Projeto</li>
        </ol>
    </nav>
    @Html.Partial("~/Views/Shared/_mensagemRetorno.cshtml")

    @using (Html.BeginForm())
    {

        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Code)
        @Html.HiddenFor(model => model.CreationDate)
        @Html.HiddenFor(model => model.CodeCreationUser)
        @Html.HiddenFor(model => model.IdcActive)
        <fieldset>
            <legend>Editar Projeto</legend>

            <div class="form-group">
                <label for="Name">Nome</label>
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = "Insira um Nome", required = true })
            </div>

            <div class="form-group">
                <label for="Value">Valor</label>
                <input value="@(Model.Value)" id="Value" name="Value" class="form-control" placeholder="Insira um Valor" required />
            </div>

            <div class="form-group">
                <label for="SubService">Tipo de Sub-Serviço</label>
                @Html.DropDownList("CodeSubService", null, "Selecione", new { @class = "selectpicker" })
            </div>

            <div class="form-group">
                <!-- Submit button !-->
                <button type="submit" class="btn btn-primary">Editar</button>
            </div>
        </fieldset>
    }

</div>

RochaGerenciamento.MVC/Views/Project/Index.cshtml
@model IEnumerable<RochaGerenciamento.Domain.Entities.Project>

@{
    ViewBag.Title = "Index";
}
<div class="innerpage">
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Principal")">Home</a></li>
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Construction")">Obras</a></li>
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Plan")">Planejamentos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Projetos</li>
        </ol>
    </nav>
    @Html.Partial("~/Views/Shared/_mensagemRetorno.cshtml")

    <button type="button" class="btn btn-default"><a href="@Url.Action("Create")">Adicionar Novo</a></button>
    @Html.Partial("~/Views/Shared/_exportFiles.cshtml")
    <div class="table-responsive">
        <table id="grid-data" class="table table-condensed table-hover table-striped" data-url="@Url.Action("List", "Project")">
            <thead>
                <tr>
                    <th data-width="10" data-column-id="Code" data-visible="false">Codigo</th>
                    <th data-width="10" data-sortable="false" data-order="asc" data-column-id="Name">Nome</th>
                    <th data-width="10" data-sortable="false" data-order="asc" data-column-id="Value">Valor</th>
                    <th data-width="10" data-sortable="false" data-order="asc" data-column-id="SubService">Sub-Serviço</th>
                    <th data-width="100" data-header-css-class="tamanho-coluna-10" data-column-id="commands" data-formatter="commands" data-sortable="false"></th>
                </tr>
            </thead>
        </table>
    </div>
    @Html.Hidden("Controller", "Project")

</div>