RochaGerenciamento.MVC/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RochaGerenciamento.Domain.Entities;
using RochaGerenciamento.Infra.Contexto;
using RochaGerenciamento.Application.Interfaces;
using RochaGerenciamento.Domain.Enums;
using RochaEmpreendimento.Utils;

namespace RochaGerenciamento.MVC.Controllers
{
    [Authorize(Roles = "administrador")]
    public class EmployeeController : BaseController<Employee>
    {
        IAppServiceBase<Position> _positionApp;
        IAppServiceBase<EmployeeStatus> _statusApp;
        public EmployeeController(IEmployeeAppService entityApp, IAppServiceBase<User> userApp, IAppServiceBase<Position> positionApp, IAppServiceBase<EmployeeStatus> statusApp)
            : base(entityApp, userApp)
        {
            _positionApp = positionApp;
            _statusApp = statusApp;
            ViewBag.CodePosition = new SelectList(_positionApp.GetAll().ToList(), GeneralField.Code, GeneralField.Name);
            ViewBag.CodeEmployeeStatus = new SelectList(_statusApp.GetAll().ToList(), GeneralField.Code, GeneralField.Name);
            ViewBag.ThirdParty = DropDownList.ListYesNo();
     
        }

        public override ActionResult Edit(int id = 0)
        {
            var entity = _entityApp.GetById(id);
            if (CheckIfExists(entity)) return RedirectToAction("Index");
            ViewBag.CodePosition = new SelectList(_positionApp.GetAll().ToList(), GeneralField.Code, GeneralField.Name, entity.CodePosition);
            ViewBag.CodeEmployeeStatus = new SelectList(_statusApp.GetAll().ToList(), GeneralField.Code, GeneralField.Name, entity.CodeEmployeeStatus);
            ViewBag.ThirdParty = DropDownList.ListYesNo(entity.ThirdParty);
            return View(entity);
        }

    }
}

RochaGerenciamento.MVC/Controllers/PositionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RochaGerenciamento.Domain.Entities;
using RochaGerenciamento.Infra.Contexto;
using RochaGerenciamento.Application.Interfaces;

namespace RochaGerenciamento.MVC.Controllers
{
    [Authorize(Roles = "administrador")]
    public class PositionController : BaseController<Position>
    {
        public PositionController(IAppServiceBase<Position> entityApp, IAppServiceBase<User> userApp)
            : base(entityApp, userApp)
        {
        }
    }
}

RochaGerenciamento.MVC/Controllers/PrincipalController.cs
using RochaGerenciamento.Application.Interfaces;
using RochaGerenciamento.Domain.Enums;
using RochaGerenciamento.MVC.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RochaGerenciamento.MVC.Controllers
{
    public class PrincipalController : Controller
    {
        IConstructionAppService _constructionAppService;
        public PrincipalController(IConstructionAppService constructionAppService)
        {
            _constructionAppService = constructionAppService;
            ViewBag.CodeConstruction = new SelectList(_constructionAppService.GetAll().ToList(), GeneralField.Code, GeneralField.Name);
        }

        public JsonResult SetSessionConstruction(int codeConstruction, string nameConstruction)
        {
            
            try
            {
                RochaGerenciamento.Domain.ValueObject.Session.CodeConstruction = codeConstruction;
                RochaGerenciamento.Domain.ValueObject.Session.NameConstruction = nameConstruction;
                return Json(new { Message = "ConstructionChosen", Success = SuccessMessage.ConstructionChosen, Error = String.Empty });
            }
            catch
            {
                return Json(new { Message = "False", Error = ErrorMessage.NotCompleted, Success = String.Empty });
            }
        } 

        public ActionResult Index()
        {
            //if (Authorizer.AutorizaEstoque)
            //    return RedirectToAction("Estoque", "Movimentacao");
            //if (Authorizer.AutorizaPlanejamento)
            //    return RedirectToAction("ItensBaixa", "Movimentacao");
            //if (Authorizer.AutorizaVendedor)
            //    return RedirectToAction("ItensVendidos", "Movimentacao");
            ViewBag.CodeConstruction = new SelectList(_constructionAppService.GetAll().ToList(), GeneralField.Code, GeneralField.Name, RochaGerenciamento.Domain.ValueObject.Session.CodeConstruction);
            return View();
        }

    }
}

RochaGerenciamento.MVC/Views/Position/Create.cshtml
@model RochaGerenciamento.Domain.Entities.Position

@{
    ViewBag.Title = "Create";
}
<div class="innerpage">
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Principal")">Home</a></li>
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Employee")">Funcionarios</a></li>
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Position")">Cargos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Criar Cargo</li>
        </ol>
    </nav>
    @Html.Partial("~/Views/Shared/_mensagemRetorno.cshtml")

    @using (Html.BeginForm())
    {

        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Criar Cargo</legend>

            <div class="form-group">
                <label for="Name">Nome</label>
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = "Insira um Nome", required = true })
            </div>



            <div class="form-group">
                <!-- Submit button !-->
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            </div>
        </fieldset>
    }

</div>

RochaGerenciamento.MVC/Views/Position/Edit.cshtml
@model RochaGerenciamento.Domain.Entities.Position

@{
    ViewBag.Title = "Edit";
}

<div class="innerpage">
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Principal")">Home</a></li>
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Employee")">Funcionarios</a></li>
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Position")">Cargos</a></li>
            <li class="breadcrumb-item active" aria-current="page">Editar Cargo</li>
        </ol>
    </nav>
    @Html.Partial("~/Views/Shared/_mensagemRetorno.cshtml")

    @using (Html.BeginForm())
    {

        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Editar Cargo</legend>

            @Html.HiddenFor(model => model.Code)
            @Html.HiddenFor(model => model.CreationDate)
            @Html.HiddenFor(model => model.CodeCreationUser)
            @Html.HiddenFor(model => model.IdcActive)
            <div class="form-group">
                <label for="Name">Nome</label>
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = "Insira um Nome", required = true })
            </div>



            <div class="form-group">
                <!-- Submit button !-->
                <button type="submit" class="btn btn-primary">Editar</button>
            </div>
        </fieldset>
    }

</div>

RochaGerenciamento.MVC/Views/Position/Index.cshtml
@model IEnumerable<RochaGerenciamento.Domain.Entities.Position>

@{
    ViewBag.Title = "Index";
}
<div class="innerpage">
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Principal")">Home</a></li>
            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Employee")">Funcionaros</a></li>
            <li class="breadcrumb-item active" aria-current="page">Cargos</li>
        </ol>
    </nav>
    @Html.Partial("~/Views/Shared/_mensagemRetorno.cshtml")

    <button type="button" class="btn btn-default"><a href="@Url.Action("Create")">Adicionar Novo</a></button>
    @Html.Partial("~/Views/Shared/_exportFiles.cshtml")
    <div class="table-responsive">
        <table id="grid-data" class="table table-condensed table-hover table-striped" data-url="@Url.Action("List", "Position")">
            <thead>
                <tr>
                    <th data-width="10" data-column-id="Code" data-visible="false">Codigo</th>
                    <th data-width="10" data-header-css-class="tamanho-coluna-20" data-sortable="false" data-order="asc" data-column-id="Name">Nome</th>
                    <th data-width="100" data-header-css-class="tamanho-coluna-10" data-column-id="commands" data-formatter="commands" data-sortable="false"></th>
                </tr>
            </thead>
        </table>
    </div>
    @Html.Hidden("Controller", "Position")

</div>